### ISSUE TITLE
Is this project viable?

### ISSUE THREAD

**Issue by buchenberg** [buchenberg/Hangfire.Realm#1]
I have an interest in this integration. Have you found anything so far that tells you that it's not going to work? If you don't think it will be too much work, I would like to contribute.

**Comment by gottscj** [comment]
@buchenberg,

Sounds good!
Im also main contributer to Hangfire.Mongo.

Its in early development. I only tested on a local db, so I havent worked with synchronized realms.

it seems to work ok, 
I can add you as contributer if you like

**Comment by buchenberg** [comment]
Thanks!
