### ISSUE TITLE
More eyeballs needed..

### ISSUE THREAD

**Issue by buchenberg** [buchenberg/Hangfire.Realm#13]
I just tagged an [alpha release](https://github.com/gottscj/Hangfire.Realm/releases/tag/v0.1-alpha) as I've gotten the extension in a state where it (mostly) works in development. I could use some feedback on a couple of items from those of you who are more familiar with both Hangfire and Realm.

Given that Realm is so different than a traditional SQL or NoSQL database, fulfilling the API contract is a bit of a challenge. Realm doesn't use locks in the same way as usual. The Hangfire API is written in a way that works well with the default SQL Server storage extension. However, some of the methods can't really be ported. Example:
```
public override IDisposable AcquireDistributedLock(string resource, TimeSpan timeout)
```
As far as I can tell, that's not really applicable to Realm. I'm just returning null and it seems to work OK. If anyone can think of a good reason or way of handling that in a way that means something to Realm I would like to hear it. Otherwise, I will likely delete the RealmDistributedLock stuff all together.

I'm also running into some issues with job id's only when it comes to Continuation jobs referencing recurring jobs. Otherwise the GUID id's are working fine. It bombs out here:

```
public override void SetJobParameter(string id, string name, string value)
```

The id value gets passed in as e.g. "some-recurring-job" rather than the expected GUID. It's odd because I can run the recurring job and I can see it in the dashboard.

Any feedback is appreciated!

**Comment by buchenberg** [comment]
Update: According to the following discourse, I am trying to run continuations on recurring jobs wrong. So that solves my second issue. Please disregard.

https://discuss.hangfire.io/t/backgroundjob-continuewith-on-a-recurringjob/1927/3

I'm still trying to wrap my head around how AcquireDistributedLock translates to Realm.

**Comment by gottscj** [comment]
@buchenberg,

Im curios why we dont need a distributedlock for realm? isnt the use case similar for SQL using transactions?
we could try to reach out to @odinserj and ask him why a distributed lock is needed for SQL server.

**Comment by buchenberg** [comment]
@gottscj 

As far as I can tell, Realm doesn't expose the same type of locking functionality. Here's a bit from the [docs](https://realm.io/docs/dotnet/latest/#threading).

> Within individual threads, you can just treat everything as regular objects without worrying about concurrency or multithreading. There is no need for any locks or resource coordination to access them (even if they are simultaneously being modified on other threads) and it is only modifying operations that have to be wrapped in transactions.

SQL Server exposes locking functionality ala carte as in the following from [a post I found on the subject.](https://www.sqlshack.com/locking-sql-server/) 

> Locking is essential to successful SQL Server transactions processing and it is designed to allow SQL Server to work seamlessly in a multi-user environment. Locking is the way that SQL Server manages transaction concurrency. Essentially, locks are in-memory structures which have owners, types, and the hash of the resource that it should protect.

So while SQL Server allows locks to be set on resources as a separate function, Realm provides locks as part of the write operation itself.

Now keep in mind that I'm not a DBA and I'm very new to Realm DB so I could be entirely wrong. For the purposes of testing, I'm just returning a null from the AcquireDistributedLock method and all of the jobs seem to run fine with multiple threads. I'll keep the handling classes around in case we need them.

Our RealmWriteOnlyTransaction class will still need a bit of work. Previously, it was opening a Realm write transaction upon instantiation and closing it when the Commit() method was called. However, when testing continuation jobs the Hangfire code left a transaction open and tried to open a new one on the same thread. I took a sort of scorched earth approach and refactored all of the methods in that class to be complete open/close write transactions. While this works for now, batching operations will be more efficient. I just need to put in a conditional that checks the transaction state and handles a situation where it's still open. I'm a little afraid to either commit or roll back that transaction until I can trace the logic from Hangfire.Core to see why it's trying to open two instances of that class on the same thread.

**Comment by gottscj** [comment]
@buchenberg,

The distributed locks are when multiple hangfire servers access the same jobqueue. Eg. multiple hangfire servers running. My guess  is that the locks are used to make sure the different hangfire instances can run atomic operations.
You can try to log the different locks hangfire tries to acquire when running different scenarios

**Comment by buchenberg** [comment]
@gottscj 

I think you are right. When I have a moment, I'll try and trace an operation and see if the persisted LockDto objects have any effect on the Realm transactions. I haven't tested multiple Hangfire servers. I suppose that might be a scenario where a more robust database would be used. I'll keep this thread open.

**Comment by buchenberg** [comment]
@gottscj 

I was able to run some load testing on our extension. I did run into some issues with the distributed lock functionality turned off. After turning it back on and making some additional changes, I was able to run over 5,000 Hangfire jobs using 10 worker threads without any issue. I think the extension is ready to be published on nuget. 

I added the extension to the[ Hangfire website](https://www.hangfire.io/extensions.html). Hopefully that will result in more usage.

**Comment by gottscj** [comment]
@buchenberg,

Sweet! Well done sir!
sorry for being absent on this project. I think I might have too many projects going! :)

**Comment by buchenberg** [comment]
@gottscj 

Thanks! If you like, I would be happy to maintain this project. I'm going to be using this extension a lot in the next year or so. It will continue to be actively developed by myself and developers on my team.

**Comment by gottscj** [comment]
@buchenberg,

Sounds awesome! Would you like me to transfer this project to your account, so you will be the owner? Then you can set the team as you wish.

You can keep me as collaborator if you like.

**Comment by buchenberg** [comment]
@gottscj 
Sorry for the delay. Yes, please. I would be happy to maintain the repo. I'll keep you as a collaborator and continue to credit you as an author. Thanks!
